var signinController = require('./signin.controller');
var passport =   require('./passport.js');
const router = require('express').Router();
router.post("/",signinController.signin);
router.post("/error",signinController.errorHandler);
router.get("/auth/facebook",passport.authenticate('facebook'));
router.get("/auth/facebook/callback",passport.authenticate('facebook', { failureRedirect: 'api/v1/signin/error' }),signinController.fbCallback);
router.get("/auth/google",passport.authenticate('google',{scope:['profile']}));
router.get("/auth/google/callback",passport.authenticate('google', { failureRedirect: 'api/v1/signin/error' }),signinController.googleCallback);
exports = module.exports = router;
